### ISSUE TITLE
More user friendly log

### ISSUE THREAD

**Issue by myajima** [RGLab/preprocessData#1]
When there are multiple process_xxx.R files, it would be nice to know which file is being processed in the log so that the user can easily figure out where to error came from.

**Comment by gfinak** [comment]
The package currently logs to inst/extdata/Logfiles. I need to investigate this more as I'd really prefer to have a complete transcript of everything that's run, currently it just gives me output but not the commands.

**Comment by gfinak** [comment]
After toying with this a bit, I'm thinking of parsing the R code as either `Rmarkdown` or using `knitr::spin()`.
We can probably do away with sourcing files from within datasets.R and just process all files in data-raw (that aren't datasets.R). These can still be run in the appropriate environment, so the rest of the code shouldn't change.

**Comment by gfinak** [comment]
Fixed by e72a10f94ece9398d3fb054620a6fccff61085ed
