### ISSUE TITLE
roxygen2 v6.0.1(released 2017-02-06) no longer has write.description().

### ISSUE THREAD

**Issue by paulobrecht** [RGLab/preprocessData#11]
This affects datapackage.skeleton().

**Comment by gfinak** [comment]
Okay, the fix here will be to take that piece of code from the old version
and add it to the package.

**Comment by gfinak** [comment]
Seems the CRAN package `desc` now has this functionality.

**Comment by gfinak** [comment]
commit d13d0c8 should address the above. give it a go and let me know.
