### ISSUE TITLE
Help files still kept even if removed from dataset.R

### ISSUE THREAD

**Issue by wfulp** [RGLab/preprocessData#5]
When removing functions the help files are kept during the buildDataSetPackage process, even though there is no longer reference to them in the dataset.R file or any other code in the data-raw folder. For example, in the AUP567 project both the backgroundSubtract.Rd and marginalize_cytokine.Rd still are help files when loading in AUP567. Should the buildDataSetPackage process eliminated no longer used Rd files in the man folder?

**Comment by gfinak** [comment]
Probably, yes.. I'll put in a fix when I get a chance. Thanks.
