### ISSUE TITLE
Error when running datapackage.skeleton()

### ISSUE THREAD

**Issue by paulobrecht** [RGLab/preprocessData#6]
I tried running datapackage.skeleton() with a range of arguments, and none at all, and I keep getting this error.

> library(preprocessData)
> datapackage.skeleton()
Error in !have : invalid argument type

> R.Version()
$platform
[1] "x86_64-unknown-linux-gnu"

$arch
[1] "x86_64"

$os
[1] "linux-gnu"

$system
[1] "x86_64, linux-gnu"

$status
[1] ""

$major
[1] "3"

$minor
[1] "1.1"

$year
[1] "2014"

$month
[1] "07"

$day
[1] "10"

$`svn rev`
[1] "66115"

$language
[1] "R"

$version.string
[1] "R version 3.1.1 (2014-07-10)"

$nickname
[1] "Sock it to Me"

**Comment by gfinak** [comment]
I can't reproduce this. Does this happen in a fresh R session? Other R versions?

**Comment by paulobrecht** [comment]
It happens in a fresh R session in 3.1.1. I may not be using the most recent version of preprocessData, because I get an install error when trying to install the most recent version due to a dependency on pandoc version >= 1.12.3 for the vignettes. From what I can find online, it is nontrivial to get pandoc installed on SUSE enterprise, which is what I use. Is that dependency necessary?

Curiously, I don't get the pandoc error when installing the latest preprocessData in R 2.15.1. But I still get the "Error in !have : invalid argument type" error when running datapackage.skeleton() in a clean session.

**Comment by paulobrecht** [comment]
Solved by google. It's not this package. It's in issue or at least quirk of utils::package.skeleton(). http://r.789695.n4.nabble.com/Creating-a-package-skeleton-with-no-flesh-td3906538.html
