### ISSUE TITLE
Loading in Individual Datasets within a Package

### ISSUE THREAD

**Issue by wfulp** [RGLab/preprocessData#7]
Is it possible to load in individual datasets within a package? For example:
> library(rpart)
> data(car90)

But this doesn't work, even though there is a specific AUP444_bama dataset:
> library(AUP444)
> data(AUP444_bama)
Warning message:
In data(AUP444_bama) : data set ‘AUP444_bama’ not found

With projects now containing many datasets from multiple assay types, it would be nice to be able to only load in specific datasets.

**Comment by gfinak** [comment]
I like the idea. I could alter the saving of data to allow loading data sets separately, and provide a load_all_datasets(“packageName”) command to load all the data from a package.

From:  Jimmy Fulp
Reply-To:  RGLab/preprocessData
Date:  Wednesday, September 2, 2015 at 2:03 PM
To:  RGLab/preprocessData
Subject:  [preprocessData] Loading in Individual Datasets within a Package (#7)


Is it possible to load in individual datasets within a package? For example:

library(rpart)
data(car90)

But this doesn't work, even though there is a specific AUP444_bama dataset:

library(AUP444)
data(AUP444_bama)
Warning message:
In data(AUP444_bama) : data set ‘AUP444_bama’ not found

With projects now containing many datasets from multiple assay types, it would be nice to be able to only load in specific datasets.

**Comment by gfinak** [comment]
When converting from a previous version of a package (where all data sets were stored in one rda file) you'll need to manually remove the old "all in one" rda file prior to regenerating the package.

**Comment by gfinak** [comment]
This is implemented in commit 6a00a and fixes the problems in issue #8
