### ISSUE TITLE
Unexpected bevahior in buildDataSetPackage()

### ISSUE THREAD

**Issue by paulobrecht** [RGLab/preprocessData#8]
Just reinstalled this package, and I'm getting some unexpected behavior.

1. I set up my code in data-raw, update datasets.R and the DESCRIPTION file, and then run buildDataSetPackage(). The first time through (before a DATADIGEST file is generated), it runs fine, creates the .rda file in data/, but exits with an unspecified error before creating the .R file in R/ and the .Rd files in man/ and does not build the tarball.

> Found 1 data objects in file datasets.R
> Saving to data
> Done
> Error in buildDataSetPackage("serumbama") : 
>   Preprocessing failed. Address the issues above and try again.

2. I then run it a second time, making no changes, including keeping DataVersion unchanged. The tarball builds successfully this time. I now have .Rd files in man/ and the .R file in R/, and even DATADIGEST, timestamped at the time of this run. However, the data/ directory is empty and the processing log shows

>> buildDataSetPackage("serumbama")
>Processing data
>Logging to inst/extdata/Logfiles/processing.log
>1  of  1 :  data-raw/datasets.R 
>**Found 1 data objects in file datasets.R**
>Processed data sets match existing data sets at version 0.1.0
>Saving to data
>Copied documentation to R/serumbama.R
>Done
>Removing old documentation.
>Building documentation
>First time using roxygen2 4.0. Upgrading automatically...
>Writing serumbama.Rd
>Writing bama.Rd
>Building package
>'/usr/local/apps/R/R-3.2.1/lib64/R/bin/R' --no-site-file --no-environ  \
>  --no-save --no-restore CMD build  \
>  '/home/pobrecht/MucosalBAMA/serum_bama/serumbama' --no-resave-data  \
>  --no-manual --no-build-vignettes 
>
>* checking for file '/home/pobrecht/MucosalBAMA/serum_bama/serumbama/DESCRIPTION' ... OK
>* preparing 'serumbama':
>* checking DESCRIPTION meta-information ... OK
>* checking for LF line-endings in source and make files
>* checking for empty or unneeded directories
>**Removed empty directory 'serumbama/data'**
>* building 'serumbama_1.0.tar.gz'

**Comment by gfinak** [comment]
I am working on a fix.


From:  Paul Obrecht
Reply-To:  RGLab/preprocessData
Date:  Wednesday, September 2, 2015 at 3:31 PM
To:  RGLab/preprocessData
Subject:  [preprocessData] Unexpected bevahior in buildDataSetPackage() (#8)


Just reinstalled this package, and I'm getting some unexpected behavior.
I set up my code in data-raw, update datasets.R and the DESCRIPTION file, and then run buildDataSetPackage(). The first time through (before a DATADIGEST file is generated), it runs fine, creates the .rda file in data/, but exits with an unspecified error before creating the .R file in R/ and the .Rd files in man/ and does not build the tarball.
Found 1 data objects in file datasets.R
Saving to data
Done
Error in buildDataSetPackage("serumbama") : 
 Preprocessing failed. Address the issues above and try again.
I then run it a second time, making no changes, including keeping DataVersion unchanged. The tarball builds successfully this time. I now have .Rd files in man/ and the .R file in R/, and even DATADIGEST, timestamped at the time of this run. However, the data/ directory is empty and the processing log shows
buildDataSetPackage("serumbama")
Processing data
Logging to inst/extdata/Logfiles/processing.log
1  of  1 :  data-raw/datasets.R 
Found 1 data objects in file datasets.R
Processed data sets match existing data sets at version 0.1.0
Saving to data
Copied documentation to R/serumbama.R
Done
Removing old documentation.
Building documentation
First time using roxygen2 4.0. Upgrading automatically...
Writing serumbama.Rd
Writing bama.Rd
Building package
'/usr/local/apps/R/R-3.2.1/lib64/R/bin/R' --no-site-file --no-environ  \
 --no-save --no-restore CMD build  \
 '/home/pobrecht/MucosalBAMA/serum_bama/serumbama' --no-resave-data  \
 --no-manual --no-build-vignettes 
checking for file '/home/pobrecht/MucosalBAMA/serum_bama/serumbama/DESCRIPTION' ... OK
preparing 'serumbama':
checking DESCRIPTION meta-information ... OK
checking for LF line-endings in source and make files
checking for empty or unneeded directories Removed empty directory 'serumbama/data'
building 'serumbama_1.0.tar.gz'

**Comment by gfinak** [comment]
Could you try pulling the branch `feature_indep_save` and see if it resolves your issue?
I've implemented independent saving of data sets so they can be loaded independently using 
`data(datasetName` rather than all at once. 
All data sets in a package would be loaded with:
`load_all_datasets(packageName)`

**Comment by paulobrecht** [comment]
Yes, I'll do that, I'll let you know how it goes.

**Comment by gfinak** [comment]
load_all_datasets is throwing some errors. I’m working on that.


From:  Paul Obrecht
Reply-To:  RGLab/preprocessData
Date:  Wednesday, September 2, 2015 at 4:00 PM
To:  RGLab/preprocessData
Cc:  Greg Finak
Subject:  Re: [preprocessData] Unexpected bevahior in buildDataSetPackage() (#8)


Yes, I'll do that, I'll let you know how it goes.
